spring:
  datasource-mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-db?useSSL=false&allowPublicKeyRetrieval=true
    username: theo
    password: theo
  datasource-h2:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:



  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    user:
      name: admin
      password: admin

  thymeleaf:
    cache: false

logging.level:
  org.hibernate:
    SQL: debug